[project]
name = "febraceapi"
version = "1.0.0"
description = "API Middleware for Febrace Analytics Platform"
authors = [
    {name = "gp2112", email="me@guip.dev"}
]

requires-python = ">= 3.9"


[project.scripts]
febraceapi = "febraceapi.__main__:main"
